name: Worlds
main: surva\worlds\Worlds
version: 3.0.4
api: 3.0.0

author: survanetwork
description: Easy to use but feature rich World Guard Plugin
website: https://plugins.surva.network/#worlds

commands:
  worlds:
    description: "Worlds plugin main command"
    usage: "/worlds list\n/worlds create <worldname> [type]\n/worlds <remove|load|unload|tp> <worldname>\n/worlds <copy|rename> <from> <to>\n/worlds set\n/worlds set legacy\n/worlds set permission <permissionstring>\n/worlds set gamemode <survival|creative|adventure|spectator>\n/worlds set <build|pvp|damage|interact|explode|drop|hunger|fly|daylightcycle> <true|false>\n/worlds unset\n/worlds unset <permission|gamemode|build|pvp|damage|interact|explode|drop|hunger|fly|daylightcycle>\n/worlds defaults\n/worlds defaults legacy\n/worlds defaults set permission <permissionstring>\n/worlds defaults set gamemode <survival|creative|adventure|spectator>\n/worlds defaults set <build|pvp|damage|interact|explode|drop|hunger|fly|daylightcycle> <true|false>\n/worlds defaults unset <permission|gamemode|build|pvp|damage|interact|explode|drop|hunger|fly|daylightcycle>"
    aliases: ["ws"]
permissions:
  worlds.list:
    description: "List existing worlds on the server"
    default: true
  worlds.admin:
    description: "Create worlds, delete worlds, set parameters, ..."
    default: op
    children:
      worlds.admin.create:
        description: "Create new worlds"
        default: op
      worlds.admin.remove:
        description: "Remove worlds"
        default: op
      worlds.admin.copy:
        description: "Copy worlds"
        default: op
      worlds.admin.rename:
        description: "Rename worlds"
        default: op
      worlds.admin.load:
        description: "Load worlds"
        default: op
      worlds.admin.unload:
        description: "Unload worlds"
        default: op
      worlds.admin.teleport:
        description: "Teleport to another world"
        default: op
      worlds.admin.set:
        description: "Set parameters (like gamemode, damage, ...)"
        default: op
      worlds.admin.unset:
        description: "Unset parameters (like gamemode, damage, ...)"
        default: op
      worlds.admin.defaults:
        description: "Set / unset world default values / parameters"
        default: op
      worlds.admin.build:
        description: "Allow building in protected worlds"
        default: op
      worlds.admin.interact:
        description: "Allow interacting in protected worlds"
        default: op
  worlds.special.gamemode:
    description: "Don't change gamemode to world's gamemode (keep it)"
    default: false
  worlds.special.fly:
    description: "Fly in every world"
    default: false
